### ISSUE TITLE
Crash when changing tape auto-clear delay ingame

### ISSUE THREAD

**Issue by alv666** [raiguard/Factorio-Tapeline#41] opened 2024-12-19 15:06 UTC
### Description

It always crashes when changing the auto-clear time from the 1 (default) to 6.

```
The mod Tapeline (3.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Tapeline::on_runtime_mod_setting_changed (ID 64)
LuaRenderObject API call when LuaRenderObject was invalid.
stack traceback:
	[C]: in function '__newindex'
	__Tapeline__/scripts/tape.lua:119: in function 'update_tape'
	__Tapeline__/scripts/tape.lua:492: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
```

**Comment by raiguard** [comment] 2024-12-23 19:18
Duplicate of #38

**Closed as not planned by raiguard** 2024-12-23 19:18 UTC
