### ISSUE TITLE
Tape tool does not work from map view

### ISSUE THREAD

**Issue by NotRexButCaesar** [raiguard/Factorio-Tapeline#19] opened 2020-11-11 21:30 UTC
When trying to measure a distance from the map view, no measurement is made.

[Any save.zip](https://github.com/raiguard/Factorio-Tapeline/files/5526843/Any.save.zip)
Select the tape tool, go to the map, and then attempt to use the tool.
Username: AmericanPatriot

[factorio-current.log](https://github.com/raiguard/Factorio-Tapeline/files/5526848/factorio-current.log)

This is probably because the tape tool is a grenade(why?) and not a selection box.

**Comment by raiguard** [comment] 2020-11-11 23:02
Duplicate of #3.

As for _why_ it uses grenades, that is the only way to get the "live" position of the mouse when dragging. The original mod used a selection tool, but the utility was greatly reduced because you would have to complete your measurement in order to see the dimensions. Using grenades, the tape can be drawn as you drag, which is infinitely more useful.

**Closed as completed by raiguard** 2020-11-11 23:02 UTC
Labels: bug, duplicate
